<?php

declare(strict_types=1);

namespace App\Migrations\Main;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260328032609 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crea tabla tenant_db para registro y gestión de bases de datos tenant';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tenant_db (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, database_name VARCHAR(255) NOT NULL, database_status VARCHAR(50) DEFAULT \'DATABASE_MIGRATED\' NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CCFEFA52989D9B62 ON tenant_db (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE tenant_db');
    }
}
