controllers_default:
    resource:
        path: ../src/Controller/Default/
        namespace: App\Controller\Default
    type: attribute

controllers_api:
    resource:
        path: ../src/Controller/Default/Api/
        namespace: App\Controller\Default\Api
    type: attribute

# 2FA routes requeridas por scheb/2fa-bundle
2fa_login:
    path: /2fa/check
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /2fa/check
    methods: [POST]
