controllers_default:
    resource:
        path: ../src/Controller/Default/
        namespace: App\Controller\Default
    type: attribute

controllers_api:
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    type: attribute

controllers_tenants:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    exclude:
        - '../src/Controller/Default/'
        - '../src/Controller/Api/'

# 2FA routes requeridas por scheb/2fa-bundle
2fa_login:
    path: /2fa/check
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /2fa/check
    methods: [POST]
