<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327193800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE facturas (id UUID NOT NULL, numero_factura VARCHAR(30) DEFAULT NULL, anio SMALLINT NOT NULL, mes SMALLINT NOT NULL, total_turnos INT NOT NULL, monto_neto NUMERIC(12, 2) NOT NULL, porcentaje_iva NUMERIC(5, 2) NOT NULL, monto_iva NUMERIC(12, 2) NOT NULL, monto_total NUMERIC(12, 2) NOT NULL, estado VARCHAR(255) NOT NULL, fecha_emision DATE DEFAULT NULL, fecha_vencimiento DATE DEFAULT NULL, fecha_pago DATE DEFAULT NULL, observaciones TEXT DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, mandante_id UUID NOT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_622B9C0F8877858D ON facturas (mandante_id)');
        $this->addSql('CREATE INDEX IDX_622B9C0FFE35D8C4 ON facturas (creado_por_id)');
        $this->addSql('CREATE TABLE items_liquidacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, concepto VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, cantidad NUMERIC(8, 2) NOT NULL, valor_unitario NUMERIC(10, 2) NOT NULL, subtotal NUMERIC(12, 2) NOT NULL, liquidacion_id UUID NOT NULL, turno_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A813E608326DAF0C ON items_liquidacion (liquidacion_id)');
        $this->addSql('CREATE INDEX IDX_A813E60869C5211E ON items_liquidacion (turno_id)');
        $this->addSql('CREATE TABLE liquidaciones_mensuales (id UUID NOT NULL, anio SMALLINT NOT NULL, mes SMALLINT NOT NULL, total_turnos INT NOT NULL, total_horas NUMERIC(8, 2) NOT NULL, monto_total NUMERIC(12, 2) NOT NULL, estado VARCHAR(255) NOT NULL, observaciones TEXT DEFAULT NULL, fecha_pago DATE DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trabajador_id UUID NOT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B32C50FEEC3656E ON liquidaciones_mensuales (trabajador_id)');
        $this->addSql('CREATE INDEX IDX_B32C50FEFE35D8C4 ON liquidaciones_mensuales (creado_por_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B32C50FEEC3656E89A505776EC83E05 ON liquidaciones_mensuales (trabajador_id, anio, mes)');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0F8877858D FOREIGN KEY (mandante_id) REFERENCES mandantes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0FFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE items_liquidacion ADD CONSTRAINT FK_A813E608326DAF0C FOREIGN KEY (liquidacion_id) REFERENCES liquidaciones_mensuales (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE items_liquidacion ADD CONSTRAINT FK_A813E60869C5211E FOREIGN KEY (turno_id) REFERENCES turnos (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE liquidaciones_mensuales ADD CONSTRAINT FK_B32C50FEEC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE liquidaciones_mensuales ADD CONSTRAINT FK_B32C50FEFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE facturas DROP CONSTRAINT FK_622B9C0F8877858D');
        $this->addSql('ALTER TABLE facturas DROP CONSTRAINT FK_622B9C0FFE35D8C4');
        $this->addSql('ALTER TABLE items_liquidacion DROP CONSTRAINT FK_A813E608326DAF0C');
        $this->addSql('ALTER TABLE items_liquidacion DROP CONSTRAINT FK_A813E60869C5211E');
        $this->addSql('ALTER TABLE liquidaciones_mensuales DROP CONSTRAINT FK_B32C50FEEC3656E');
        $this->addSql('ALTER TABLE liquidaciones_mensuales DROP CONSTRAINT FK_B32C50FEFE35D8C4');
        $this->addSql('DROP TABLE facturas');
        $this->addSql('DROP TABLE items_liquidacion');
        $this->addSql('DROP TABLE liquidaciones_mensuales');
    }
}
