<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327184025 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bitacora_operativa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tipo VARCHAR(255) NOT NULL, descripcion TEXT NOT NULL, paciente_id UUID NOT NULL, creado_por_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BF9F65D7310DAD4 ON bitacora_operativa (paciente_id)');
        $this->addSql('CREATE INDEX IDX_5BF9F65DFE35D8C4 ON bitacora_operativa (creado_por_id)');
        $this->addSql('CREATE TABLE condicion_domicilio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, acceso_descripcion TEXT DEFAULT NULL, tiene_mascotas BOOLEAN NOT NULL, mascotas_detalle VARCHAR(255) DEFAULT NULL, tiene_barreras_arquitectonicas BOOLEAN NOT NULL, barreras_detalle TEXT DEFAULT NULL, observaciones_seguridad TEXT DEFAULT NULL, requiere_ascensor BOOLEAN NOT NULL, codigo_acceso VARCHAR(10) DEFAULT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paciente_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FCA7566F7310DAD4 ON condicion_domicilio (paciente_id)');
        $this->addSql('CREATE TABLE historial_comunicacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(255) NOT NULL, contacto VARCHAR(200) DEFAULT NULL, descripcion TEXT NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paciente_id UUID NOT NULL, creado_por_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_982C73027310DAD4 ON historial_comunicacion (paciente_id)');
        $this->addSql('CREATE INDEX IDX_982C7302FE35D8C4 ON historial_comunicacion (creado_por_id)');
        $this->addSql('CREATE TABLE mandantes (id UUID NOT NULL, nombre VARCHAR(200) NOT NULL, rut VARCHAR(20) NOT NULL, contacto VARCHAR(150) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, telefono VARCHAR(20) DEFAULT NULL, activo BOOLEAN NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E25D09A9AD145DBA ON mandantes (rut)');
        $this->addSql('CREATE TABLE pacientes (id UUID NOT NULL, nombres VARCHAR(150) NOT NULL, apellidos VARCHAR(150) NOT NULL, rut VARCHAR(15) NOT NULL, fecha_nacimiento DATE DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, comuna VARCHAR(100) DEFAULT NULL, region VARCHAR(100) DEFAULT NULL, telefono VARCHAR(20) DEFAULT NULL, telefono_emergencia VARCHAR(20) DEFAULT NULL, tipo_servicio VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, fecha_ingreso DATE DEFAULT NULL, fecha_termino DATE DEFAULT NULL, tutor_nombre VARCHAR(200) DEFAULT NULL, tutor_telefono VARCHAR(20) DEFAULT NULL, tutor_relacion VARCHAR(100) DEFAULT NULL, observaciones TEXT DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, mandante_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_971B7851AD145DBA ON pacientes (rut)');
        $this->addSql('CREATE INDEX IDX_971B78518877858D ON pacientes (mandante_id)');
        $this->addSql('ALTER TABLE bitacora_operativa ADD CONSTRAINT FK_5BF9F65D7310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bitacora_operativa ADD CONSTRAINT FK_5BF9F65DFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE condicion_domicilio ADD CONSTRAINT FK_FCA7566F7310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historial_comunicacion ADD CONSTRAINT FK_982C73027310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historial_comunicacion ADD CONSTRAINT FK_982C7302FE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pacientes ADD CONSTRAINT FK_971B78518877858D FOREIGN KEY (mandante_id) REFERENCES mandantes (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bitacora_operativa DROP CONSTRAINT FK_5BF9F65D7310DAD4');
        $this->addSql('ALTER TABLE bitacora_operativa DROP CONSTRAINT FK_5BF9F65DFE35D8C4');
        $this->addSql('ALTER TABLE condicion_domicilio DROP CONSTRAINT FK_FCA7566F7310DAD4');
        $this->addSql('ALTER TABLE historial_comunicacion DROP CONSTRAINT FK_982C73027310DAD4');
        $this->addSql('ALTER TABLE historial_comunicacion DROP CONSTRAINT FK_982C7302FE35D8C4');
        $this->addSql('ALTER TABLE pacientes DROP CONSTRAINT FK_971B78518877858D');
        $this->addSql('DROP TABLE bitacora_operativa');
        $this->addSql('DROP TABLE condicion_domicilio');
        $this->addSql('DROP TABLE historial_comunicacion');
        $this->addSql('DROP TABLE mandantes');
        $this->addSql('DROP TABLE pacientes');
    }
}
