<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327192330 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE eventos_adversos (id UUID NOT NULL, fecha_evento DATE NOT NULL, hora_evento TIME(0) WITHOUT TIME ZONE DEFAULT NULL, tipo VARCHAR(255) NOT NULL, gravedad VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, descripcion TEXT NOT NULL, acciones_tomadas TEXT DEFAULT NULL, notificado_familia BOOLEAN NOT NULL, notificado_medico BOOLEAN NOT NULL, fecha_cierre DATE DEFAULT NULL, observacion_cierre TEXT DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paciente_id UUID NOT NULL, trabajador_id UUID DEFAULT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70627DBB7310DAD4 ON eventos_adversos (paciente_id)');
        $this->addSql('CREATE INDEX IDX_70627DBBEC3656E ON eventos_adversos (trabajador_id)');
        $this->addSql('CREATE INDEX IDX_70627DBBFE35D8C4 ON eventos_adversos (creado_por_id)');
        $this->addSql('CREATE TABLE seguimientos_evento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nota TEXT NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, evento_id UUID NOT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BDC9177F87A5F842 ON seguimientos_evento (evento_id)');
        $this->addSql('CREATE INDEX IDX_BDC9177FFE35D8C4 ON seguimientos_evento (creado_por_id)');
        $this->addSql('ALTER TABLE eventos_adversos ADD CONSTRAINT FK_70627DBB7310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE eventos_adversos ADD CONSTRAINT FK_70627DBBEC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE eventos_adversos ADD CONSTRAINT FK_70627DBBFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seguimientos_evento ADD CONSTRAINT FK_BDC9177F87A5F842 FOREIGN KEY (evento_id) REFERENCES eventos_adversos (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seguimientos_evento ADD CONSTRAINT FK_BDC9177FFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE eventos_adversos DROP CONSTRAINT FK_70627DBB7310DAD4');
        $this->addSql('ALTER TABLE eventos_adversos DROP CONSTRAINT FK_70627DBBEC3656E');
        $this->addSql('ALTER TABLE eventos_adversos DROP CONSTRAINT FK_70627DBBFE35D8C4');
        $this->addSql('ALTER TABLE seguimientos_evento DROP CONSTRAINT FK_BDC9177F87A5F842');
        $this->addSql('ALTER TABLE seguimientos_evento DROP CONSTRAINT FK_BDC9177FFE35D8C4');
        $this->addSql('DROP TABLE eventos_adversos');
        $this->addSql('DROP TABLE seguimientos_evento');
    }
}
