<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327185829 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE disponibilidad_trabajador (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha DATE NOT NULL, hora_desde TIME(0) WITHOUT TIME ZONE DEFAULT NULL, hora_hasta TIME(0) WITHOUT TIME ZONE DEFAULT NULL, disponible BOOLEAN NOT NULL, observacion VARCHAR(255) DEFAULT NULL, trabajador_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D838D311EC3656E ON disponibilidad_trabajador (trabajador_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D838D311EC3656E1A8B7D9 ON disponibilidad_trabajador (trabajador_id, fecha)');
        $this->addSql('CREATE TABLE trabajadores (id UUID NOT NULL, nombres VARCHAR(150) NOT NULL, apellidos VARCHAR(150) NOT NULL, rut VARCHAR(15) NOT NULL, perfil VARCHAR(255) NOT NULL, telefono VARCHAR(20) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, estado VARCHAR(255) NOT NULL, fecha_ingreso DATE DEFAULT NULL, fecha_salida DATE DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF4C0B49AD145DBA ON trabajadores (rut)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF4C0B49A76ED395 ON trabajadores (user_id)');
        $this->addSql('CREATE TABLE turnos (id UUID NOT NULL, fecha DATE NOT NULL, hora_inicio TIME(0) WITHOUT TIME ZONE NOT NULL, hora_termino TIME(0) WITHOUT TIME ZONE NOT NULL, tipo_turno VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, es_reemplazo BOOLEAN NOT NULL, motivo_reemplazo VARCHAR(255) DEFAULT NULL, registro_inicio TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, registro_termino TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observaciones TEXT DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paciente_id UUID NOT NULL, trabajador_id UUID DEFAULT NULL, turno_original_id UUID DEFAULT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B85558187310DAD4 ON turnos (paciente_id)');
        $this->addSql('CREATE INDEX IDX_B8555818EC3656E ON turnos (trabajador_id)');
        $this->addSql('CREATE INDEX IDX_B85558188E90C9F2 ON turnos (turno_original_id)');
        $this->addSql('CREATE INDEX IDX_B8555818FE35D8C4 ON turnos (creado_por_id)');
        $this->addSql('ALTER TABLE disponibilidad_trabajador ADD CONSTRAINT FK_D838D311EC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trabajadores ADD CONSTRAINT FK_CF4C0B49A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B85558187310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B8555818EC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B85558188E90C9F2 FOREIGN KEY (turno_original_id) REFERENCES turnos (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B8555818FE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE disponibilidad_trabajador DROP CONSTRAINT FK_D838D311EC3656E');
        $this->addSql('ALTER TABLE trabajadores DROP CONSTRAINT FK_CF4C0B49A76ED395');
        $this->addSql('ALTER TABLE turnos DROP CONSTRAINT FK_B85558187310DAD4');
        $this->addSql('ALTER TABLE turnos DROP CONSTRAINT FK_B8555818EC3656E');
        $this->addSql('ALTER TABLE turnos DROP CONSTRAINT FK_B85558188E90C9F2');
        $this->addSql('ALTER TABLE turnos DROP CONSTRAINT FK_B8555818FE35D8C4');
        $this->addSql('DROP TABLE disponibilidad_trabajador');
        $this->addSql('DROP TABLE trabajadores');
        $this->addSql('DROP TABLE turnos');
    }
}
