<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260328000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Esquema inicial del tenant: todas las tablas de dominio';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, email VARCHAR(180) NOT NULL, nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, activo BOOLEAN NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');

        $this->addSql('CREATE TABLE mandantes (id UUID NOT NULL, nombre VARCHAR(200) NOT NULL, rut VARCHAR(20) NOT NULL, contacto VARCHAR(150) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, telefono VARCHAR(20) DEFAULT NULL, activo BOOLEAN NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E25D09A9AD145DBA ON mandantes (rut)');

        $this->addSql('CREATE TABLE pacientes (id UUID NOT NULL, nombres VARCHAR(150) NOT NULL, apellidos VARCHAR(150) NOT NULL, rut VARCHAR(15) NOT NULL, fecha_nacimiento DATE DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, comuna VARCHAR(100) DEFAULT NULL, region VARCHAR(100) DEFAULT NULL, telefono VARCHAR(20) DEFAULT NULL, telefono_emergencia VARCHAR(20) DEFAULT NULL, tipo_servicio VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, fecha_ingreso DATE DEFAULT NULL, fecha_termino DATE DEFAULT NULL, tutor_nombre VARCHAR(200) DEFAULT NULL, tutor_telefono VARCHAR(20) DEFAULT NULL, tutor_relacion VARCHAR(100) DEFAULT NULL, observaciones TEXT DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, mandante_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_971B7851AD145DBA ON pacientes (rut)');
        $this->addSql('CREATE INDEX IDX_971B78518877858D ON pacientes (mandante_id)');

        $this->addSql('CREATE TABLE trabajadores (id UUID NOT NULL, nombres VARCHAR(150) NOT NULL, apellidos VARCHAR(150) NOT NULL, rut VARCHAR(15) NOT NULL, perfil VARCHAR(255) NOT NULL, telefono VARCHAR(20) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, estado VARCHAR(255) NOT NULL, fecha_ingreso DATE DEFAULT NULL, fecha_salida DATE DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF4C0B49AD145DBA ON trabajadores (rut)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF4C0B49A76ED395 ON trabajadores (user_id)');

        $this->addSql('CREATE TABLE turnos (id UUID NOT NULL, fecha DATE NOT NULL, hora_inicio TIME(0) WITHOUT TIME ZONE NOT NULL, hora_termino TIME(0) WITHOUT TIME ZONE NOT NULL, tipo_turno VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, es_reemplazo BOOLEAN NOT NULL, motivo_reemplazo VARCHAR(255) DEFAULT NULL, registro_inicio TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, registro_termino TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observaciones TEXT DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paciente_id UUID NOT NULL, trabajador_id UUID DEFAULT NULL, turno_original_id UUID DEFAULT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B85558187310DAD4 ON turnos (paciente_id)');
        $this->addSql('CREATE INDEX IDX_B8555818EC3656E ON turnos (trabajador_id)');
        $this->addSql('CREATE INDEX IDX_B85558188E90C9F2 ON turnos (turno_original_id)');
        $this->addSql('CREATE INDEX IDX_B8555818FE35D8C4 ON turnos (creado_por_id)');

        $this->addSql('CREATE TABLE liquidaciones_mensuales (id UUID NOT NULL, anio SMALLINT NOT NULL, mes SMALLINT NOT NULL, total_turnos INT NOT NULL, total_horas NUMERIC(8, 2) NOT NULL, monto_total NUMERIC(12, 2) NOT NULL, estado VARCHAR(255) NOT NULL, observaciones TEXT DEFAULT NULL, fecha_pago DATE DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trabajador_id UUID NOT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B32C50FEEC3656E ON liquidaciones_mensuales (trabajador_id)');
        $this->addSql('CREATE INDEX IDX_B32C50FEFE35D8C4 ON liquidaciones_mensuales (creado_por_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B32C50FEEC3656E89A505776EC83E05 ON liquidaciones_mensuales (trabajador_id, anio, mes)');

        $this->addSql('CREATE TABLE items_liquidacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, concepto VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, cantidad NUMERIC(8, 2) NOT NULL, valor_unitario NUMERIC(10, 2) NOT NULL, subtotal NUMERIC(12, 2) NOT NULL, liquidacion_id UUID NOT NULL, turno_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A813E608326DAF0C ON items_liquidacion (liquidacion_id)');
        $this->addSql('CREATE INDEX IDX_A813E60869C5211E ON items_liquidacion (turno_id)');

        $this->addSql('CREATE TABLE facturas (id UUID NOT NULL, numero_factura VARCHAR(30) DEFAULT NULL, anio SMALLINT NOT NULL, mes SMALLINT NOT NULL, total_turnos INT NOT NULL, monto_neto NUMERIC(12, 2) NOT NULL, porcentaje_iva NUMERIC(5, 2) NOT NULL, monto_iva NUMERIC(12, 2) NOT NULL, monto_total NUMERIC(12, 2) NOT NULL, estado VARCHAR(255) NOT NULL, fecha_emision DATE DEFAULT NULL, fecha_vencimiento DATE DEFAULT NULL, fecha_pago DATE DEFAULT NULL, observaciones TEXT DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, mandante_id UUID NOT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_622B9C0F8877858D ON facturas (mandante_id)');
        $this->addSql('CREATE INDEX IDX_622B9C0FFE35D8C4 ON facturas (creado_por_id)');

        $this->addSql('CREATE TABLE bitacora_operativa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tipo VARCHAR(255) NOT NULL, descripcion TEXT NOT NULL, paciente_id UUID NOT NULL, creado_por_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BF9F65D7310DAD4 ON bitacora_operativa (paciente_id)');
        $this->addSql('CREATE INDEX IDX_5BF9F65DFE35D8C4 ON bitacora_operativa (creado_por_id)');

        $this->addSql('CREATE TABLE condicion_domicilio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, acceso_descripcion TEXT DEFAULT NULL, tiene_mascotas BOOLEAN NOT NULL, mascotas_detalle VARCHAR(255) DEFAULT NULL, tiene_barreras_arquitectonicas BOOLEAN NOT NULL, barreras_detalle TEXT DEFAULT NULL, observaciones_seguridad TEXT DEFAULT NULL, requiere_ascensor BOOLEAN NOT NULL, codigo_acceso VARCHAR(10) DEFAULT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paciente_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FCA7566F7310DAD4 ON condicion_domicilio (paciente_id)');

        $this->addSql('CREATE TABLE disponibilidad_trabajador (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha DATE NOT NULL, hora_desde TIME(0) WITHOUT TIME ZONE DEFAULT NULL, hora_hasta TIME(0) WITHOUT TIME ZONE DEFAULT NULL, disponible BOOLEAN NOT NULL, observacion VARCHAR(255) DEFAULT NULL, trabajador_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D838D311EC3656E ON disponibilidad_trabajador (trabajador_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D838D311EC3656E1A8B7D9 ON disponibilidad_trabajador (trabajador_id, fecha)');

        $this->addSql('CREATE TABLE documentos_trabajador (id UUID NOT NULL, tipo VARCHAR(255) NOT NULL, nombre_original VARCHAR(255) NOT NULL, ruta_archivo VARCHAR(255) NOT NULL, extension VARCHAR(20) NOT NULL, tamano_bytes INT NOT NULL, descripcion VARCHAR(500) DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trabajador_id UUID NOT NULL, subido_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C844647EEC3656E ON documentos_trabajador (trabajador_id)');
        $this->addSql('CREATE INDEX IDX_C844647E446C2E6 ON documentos_trabajador (subido_por_id)');

        $this->addSql('CREATE TABLE eventos_adversos (id UUID NOT NULL, fecha_evento DATE NOT NULL, hora_evento TIME(0) WITHOUT TIME ZONE DEFAULT NULL, tipo VARCHAR(255) NOT NULL, gravedad VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, descripcion TEXT NOT NULL, acciones_tomadas TEXT DEFAULT NULL, notificado_familia BOOLEAN NOT NULL, notificado_medico BOOLEAN NOT NULL, fecha_cierre DATE DEFAULT NULL, observacion_cierre TEXT DEFAULT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado_en TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paciente_id UUID NOT NULL, trabajador_id UUID DEFAULT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70627DBB7310DAD4 ON eventos_adversos (paciente_id)');
        $this->addSql('CREATE INDEX IDX_70627DBBEC3656E ON eventos_adversos (trabajador_id)');
        $this->addSql('CREATE INDEX IDX_70627DBBFE35D8C4 ON eventos_adversos (creado_por_id)');

        $this->addSql('CREATE TABLE historial_comunicacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(255) NOT NULL, contacto VARCHAR(200) DEFAULT NULL, descripcion TEXT NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paciente_id UUID NOT NULL, creado_por_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_982C73027310DAD4 ON historial_comunicacion (paciente_id)');
        $this->addSql('CREATE INDEX IDX_982C7302FE35D8C4 ON historial_comunicacion (creado_por_id)');

        $this->addSql('CREATE TABLE seguimientos_evento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nota TEXT NOT NULL, creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, evento_id UUID NOT NULL, creado_por_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BDC9177F87A5F842 ON seguimientos_evento (evento_id)');
        $this->addSql('CREATE INDEX IDX_BDC9177FFE35D8C4 ON seguimientos_evento (creado_por_id)');

        $this->addSql('CREATE TABLE ext_log_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(8) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data JSON DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX log_class_lookup_idx ON ext_log_entries (object_class)');
        $this->addSql('CREATE INDEX log_date_lookup_idx ON ext_log_entries (logged_at)');
        $this->addSql('CREATE INDEX log_user_lookup_idx ON ext_log_entries (username)');
        $this->addSql('CREATE INDEX log_version_lookup_idx ON ext_log_entries (object_id, object_class, version)');

        // Foreign keys
        $this->addSql('ALTER TABLE bitacora_operativa ADD CONSTRAINT FK_5BF9F65D7310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bitacora_operativa ADD CONSTRAINT FK_5BF9F65DFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE condicion_domicilio ADD CONSTRAINT FK_FCA7566F7310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disponibilidad_trabajador ADD CONSTRAINT FK_D838D311EC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE documentos_trabajador ADD CONSTRAINT FK_C844647EEC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE documentos_trabajador ADD CONSTRAINT FK_C844647E446C2E6 FOREIGN KEY (subido_por_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE eventos_adversos ADD CONSTRAINT FK_70627DBB7310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE eventos_adversos ADD CONSTRAINT FK_70627DBBEC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE eventos_adversos ADD CONSTRAINT FK_70627DBBFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0F8877858D FOREIGN KEY (mandante_id) REFERENCES mandantes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE facturas ADD CONSTRAINT FK_622B9C0FFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE historial_comunicacion ADD CONSTRAINT FK_982C73027310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE historial_comunicacion ADD CONSTRAINT FK_982C7302FE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE items_liquidacion ADD CONSTRAINT FK_A813E608326DAF0C FOREIGN KEY (liquidacion_id) REFERENCES liquidaciones_mensuales (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE items_liquidacion ADD CONSTRAINT FK_A813E60869C5211E FOREIGN KEY (turno_id) REFERENCES turnos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE liquidaciones_mensuales ADD CONSTRAINT FK_B32C50FEEC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE liquidaciones_mensuales ADD CONSTRAINT FK_B32C50FEFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pacientes ADD CONSTRAINT FK_971B78518877858D FOREIGN KEY (mandante_id) REFERENCES mandantes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguimientos_evento ADD CONSTRAINT FK_BDC9177F87A5F842 FOREIGN KEY (evento_id) REFERENCES eventos_adversos (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguimientos_evento ADD CONSTRAINT FK_BDC9177FFE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trabajadores ADD CONSTRAINT FK_CF4C0B49A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B85558187310DAD4 FOREIGN KEY (paciente_id) REFERENCES pacientes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B8555818EC3656E FOREIGN KEY (trabajador_id) REFERENCES trabajadores (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B85558188E90C9F2 FOREIGN KEY (turno_original_id) REFERENCES turnos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B8555818FE35D8C4 FOREIGN KEY (creado_por_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE bitacora_operativa DROP CONSTRAINT FK_5BF9F65D7310DAD4');
        $this->addSql('ALTER TABLE bitacora_operativa DROP CONSTRAINT FK_5BF9F65DFE35D8C4');
        $this->addSql('ALTER TABLE condicion_domicilio DROP CONSTRAINT FK_FCA7566F7310DAD4');
        $this->addSql('ALTER TABLE disponibilidad_trabajador DROP CONSTRAINT FK_D838D311EC3656E');
        $this->addSql('ALTER TABLE documentos_trabajador DROP CONSTRAINT FK_C844647EEC3656E');
        $this->addSql('ALTER TABLE documentos_trabajador DROP CONSTRAINT FK_C844647E446C2E6');
        $this->addSql('ALTER TABLE eventos_adversos DROP CONSTRAINT FK_70627DBB7310DAD4');
        $this->addSql('ALTER TABLE eventos_adversos DROP CONSTRAINT FK_70627DBBEC3656E');
        $this->addSql('ALTER TABLE eventos_adversos DROP CONSTRAINT FK_70627DBBFE35D8C4');
        $this->addSql('ALTER TABLE facturas DROP CONSTRAINT FK_622B9C0F8877858D');
        $this->addSql('ALTER TABLE facturas DROP CONSTRAINT FK_622B9C0FFE35D8C4');
        $this->addSql('ALTER TABLE historial_comunicacion DROP CONSTRAINT FK_982C73027310DAD4');
        $this->addSql('ALTER TABLE historial_comunicacion DROP CONSTRAINT FK_982C7302FE35D8C4');
        $this->addSql('ALTER TABLE items_liquidacion DROP CONSTRAINT FK_A813E608326DAF0C');
        $this->addSql('ALTER TABLE items_liquidacion DROP CONSTRAINT FK_A813E60869C5211E');
        $this->addSql('ALTER TABLE liquidaciones_mensuales DROP CONSTRAINT FK_B32C50FEEC3656E');
        $this->addSql('ALTER TABLE liquidaciones_mensuales DROP CONSTRAINT FK_B32C50FEFE35D8C4');
        $this->addSql('ALTER TABLE pacientes DROP CONSTRAINT FK_971B78518877858D');
        $this->addSql('ALTER TABLE seguimientos_evento DROP CONSTRAINT FK_BDC9177F87A5F842');
        $this->addSql('ALTER TABLE seguimientos_evento DROP CONSTRAINT FK_BDC9177FFE35D8C4');
        $this->addSql('ALTER TABLE trabajadores DROP CONSTRAINT FK_CF4C0B49A76ED395');
        $this->addSql('ALTER TABLE turnos DROP CONSTRAINT FK_B85558187310DAD4');
        $this->addSql('ALTER TABLE turnos DROP CONSTRAINT FK_B8555818EC3656E');
        $this->addSql('ALTER TABLE turnos DROP CONSTRAINT FK_B85558188E90C9F2');
        $this->addSql('ALTER TABLE turnos DROP CONSTRAINT FK_B8555818FE35D8C4');

        $this->addSql('DROP TABLE seguimientos_evento');
        $this->addSql('DROP TABLE eventos_adversos');
        $this->addSql('DROP TABLE historial_comunicacion');
        $this->addSql('DROP TABLE bitacora_operativa');
        $this->addSql('DROP TABLE condicion_domicilio');
        $this->addSql('DROP TABLE disponibilidad_trabajador');
        $this->addSql('DROP TABLE documentos_trabajador');
        $this->addSql('DROP TABLE items_liquidacion');
        $this->addSql('DROP TABLE facturas');
        $this->addSql('DROP TABLE liquidaciones_mensuales');
        $this->addSql('DROP TABLE turnos');
        $this->addSql('DROP TABLE pacientes');
        $this->addSql('DROP TABLE trabajadores');
        $this->addSql('DROP TABLE mandantes');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE users');
    }
}
